services:
  db:
    image: postgres
    restart: always
    volumes:
      - timetable-api-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.timetable-api-adminer.rule=Host(`${PGADMIN_TRAEFIK_HOST}`)
      - traefik.http.routers.timetable-api-adminer.entrypoints=https
      - traefik.http.services.timetable-api-adminer.loadbalancer.server.port=8080

volumes:
  timetable-api-pgdata:

networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
