[package]
name = "timetable-api-crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.193", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["runtime-tokio", "postgres", "chrono", "ipnetwork"] }
dotenvy = "0.15.7"
reqwest = "0.12.4"
scraper = "0.19.0"
url = "2.5.0"
lazy_static = "1.4.0"
aho-corasick = "1.1.3"
regex = "1.10.4"
futures = "0.3.30"
indicatif = "0.17.8"
