[package]
name = "timetable-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.193", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["runtime-tokio", "postgres", "chrono", "ipnetwork"] }
dotenvy = "0.15.7"
regex = "1.10.2"
regex-macro = "0.2.0"
chrono = { version = "0.4.31", features = ["serde"] }
email_address = "0.2.4"
aide = { version = "0.13.1", features = ["axum", "macros", "redoc"] }
schemars = { version = "0.8.16", features = ["raw_value"] }
axum-jsonschema = { version = "0.8.0", features = ["aide"] }
serde_json = { version = "1.0.111", features = ["raw_value"] }
